# Generated by Django 4.2.1 on 2023-05-26 23:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0004_alter_diabetesdetection_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diabetesdetection",
            old_name="Age",
            new_name="age",
        ),
        migrations.RenameField(
            model_name="diabetesdetection",
            old_name="Cholesterol",
            new_name="cholesterol",
        ),
        migrations.RenameField(
            model_name="diabetesdetection",
            old_name="Diastolic_BP",
            new_name="diastolic_bp",
        ),
        migrations.RenameField(
            model_name="diabetesdetection",
            old_name="Gender",
            new_name="gender",
        ),
        migrations.RenameField(
            model_name="diabetesdetection",
            old_name="Glucose",
            new_name="glucose",
        ),
        migrations.RenameField(
            model_name="diabetesdetection",
            old_name="Hdl_CholL",
            new_name="hdl_choll",
        ),
        migrations.RenameField(
            model_name="diabetesdetection",
            old_name="Systolic_BP",
            new_name="systolic_bp",
        ),
        migrations.RenameField(
            model_name="diabetesdetection",
            old_name="Weight",
            new_name="weight",
        ),
        migrations.RenameField(
            model_name="gestationaldiabetes",
            old_name="Age",
            new_name="age",
        ),
        migrations.RenameField(
            model_name="gestationaldiabetes",
            old_name="BP_level",
            new_name="bp_level",
        ),
        migrations.RenameField(
            model_name="gestationaldiabetes",
            old_name="Diabetes_Pedigree",
            new_name="diabetes_pedigree",
        ),
        migrations.RenameField(
            model_name="gestationaldiabetes",
            old_name="Glucose",
            new_name="glucose",
        ),
        migrations.RenameField(
            model_name="gestationaldiabetes",
            old_name="Insulin",
            new_name="insulin",
        ),
        migrations.RenameField(
            model_name="gestationaldiabetes",
            old_name="Number_Of_Pregnancies",
            new_name="number_of_pregnancies",
        ),
        migrations.RenameField(
            model_name="gestationaldiabetes",
            old_name="Skin_Thickness",
            new_name="skin_thickness",
        ),
    ]
