# Generated by Django 4.2.1 on 2023-05-26 23:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0006_rename_age_diabetesdetection_ageee_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diabetesdetection",
            old_name="ageee",
            new_name="age",
        ),
    ]
