# Generated by Django 4.2.1 on 2023-05-26 23:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0007_rename_ageee_diabetesdetection_age"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diabetesdetection",
            old_name="age",
            new_name="age43",
        ),
    ]
