# Generated by Django 4.2.1 on 2023-05-26 23:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0008_rename_age_diabetesdetection_age43"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diabetesdetection",
            old_name="age43",
            new_name="age",
        ),
    ]
