# Generated by Django 4.2.1 on 2023-05-31 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0011_alter_patient_doctor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="doctor",
        ),
    ]
