# Generated by Django 4.2.1 on 2023-05-31 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0015_alter_diabetesdetectiondoctor_result_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diabetesdetectiondoctor",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 5, 31, 16, 2, 56, 101841, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="diabetesdetectionpatient",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 5, 31, 16, 3, 4, 934354, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gestationaldiabetesdoctor",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 5, 31, 16, 4, 8, 329435, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gestationaldiabetespatient",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 5, 31, 16, 4, 11, 24113, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
