# Generated by Django 4.2.1 on 2023-05-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0017_diabetesdetectiondoctor_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diabetesdetectionpatient",
            name="height",
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="diabetesdetectionpatient",
            name="phone",
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gestationaldiabetespatient",
            name="height",
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gestationaldiabetespatient",
            name="phone",
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
