# Generated by Django 4.2.1 on 2023-05-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0018_diabetesdetectionpatient_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diabetesdetectiondoctor",
            name="type",
            field=models.CharField(
                default="Diabetes Detection", max_length=150, null=True
            ),
        ),
        migrations.AddField(
            model_name="diabetesdetectionpatient",
            name="type",
            field=models.CharField(
                default="Diabetes Detection", max_length=150, null=True
            ),
        ),
        migrations.AddField(
            model_name="gestationaldiabetesdoctor",
            name="type",
            field=models.CharField(
                default="Gestational Diabetes Detection", max_length=150, null=True
            ),
        ),
        migrations.AddField(
            model_name="gestationaldiabetespatient",
            name="type",
            field=models.CharField(
                default="Gestational Diabetes Detection", max_length=150, null=True
            ),
        ),
    ]
