# Generated by Django 4.2.1 on 2023-07-04 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0023_alter_diabetesdetectiondoctor_result_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetinopathyDetectionPatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        default="Retinopathy Detection", max_length=150, null=True
                    ),
                ),
                ("result", models.CharField(max_length=150)),
                ("date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.patient"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RetinopathyDetectionDoctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        default="Retinopathy Detection", max_length=150, null=True
                    ),
                ),
                ("result", models.CharField(max_length=150)),
                ("date", models.DateTimeField(auto_now_add=True, null=True)),
                ("patient_name", models.CharField(max_length=150)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.doctor"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
